blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import all_blogs, post

app_name = 'blog'

urlpatterns = [
    path('', all_blogs, name='all_blogs'),
    path('<str:post_title>', post),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from portfolio.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    addition_time = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio', blank=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from .models import Blog
from django.shortcuts import get_object_or_404



def all_blogs(request):
    blogs = Blog.objects.all()
    return render(request, r'blog/all_blogs.html', {'blogs': blogs, 'posts_count': len(blogs)})


def post(request, post_title):
    post = get_object_or_404(Blog, title=post_title)
    print(post.title)
    return render(request, r'blog/post.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

app_name = 'portfolio'


def home(request):
    projects = Project.objects.all()
    return render(request, r'portfolio/home.html', {'projects': projects})

templates/blog/all_blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'portfolio/base.html' %}
{% block content %}
<h1>Blog</h1>
<h2>Pawel was written {{ posts_count }} blog{{ posts_count|pluralize}}</h2>
{% for blog in blogs %}
<h2>
    <a href="{{ blog.title }}"> {{ blog.title }} </a>
</h2>
<p>
    <font color="gray">
        {{ blog.addition_time }}
    </font>
</p>
<p>
    {{ blog.content | truncatechars:100 }}
</p>
{% endfor %}
{% endblock %}
</body>
</html>

templates/blog/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'portfolio/base.html' %}
{% block content %}
<h1>{{ post.title }}</h1>
<p>{{ post.content }}</p>
Added at: <font color="gray">{{post.addition_time}}</font>
{% endblock %}
</body>
</html>

templates/portfolio/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <title>Hello from base</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Pavel's portfolio</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" target="_blank" href="https://t.me/Christian_Tyler">
                        Telegram
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" target="_blank" href="https://vk.com/id137549524">
                        Vk
                    </a>
                </li>
                <li class="nav-item">
                    <a role="button" class="btn btn-primary" href="{% url 'blog:all_blogs' %}">Blog</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %} {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/portfolio/home.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Pavel Lebedev</title>
</head>
<body>
{% extends 'portfolio/base.html' %}
{% block content %}

{% load static %}

<div class="row justify-content-center my-3">
    <div class="col-5">
        <img class="img-fluid" src="{% static 'portfolio/resumeImage.png' %}">
    </div>
</div>

<div class="mt-2">
    <h1>Portfolio</h1>
</div>
<div class="row">
    {% for project in projects %}
    <div class="col-lg-4 col-md-6">

        {% if project.url %}
        <a href="{{ project.url }}">
            <img class="img-fluid mb-2" src="{{ project.image.url }}">
        </a>
        {% else %}
        <img class="img-fluid mb-2" src="{{ project.image.url }}">
        {% endif %}
        <h3>{{ project.name }}</h3>
    </div>

    {% endfor %}

</div>

{% endblock %}
</body>
</html>